### ISSUE TITLE
TODO TODAY [enter] returns empty

### ISSUE THREAD

**Issue by haakonstorm** [xilopaint/alfred-things#8] opened 2019-04-18 16:19 UTC
TODO TODAY [enter] returns empty
All the other lists works
Great workflow!
How to fix "today"? :)

**Comment by xilopaint** [comment] 2019-04-19 02:43
I can't reproduce your issue. Any chance you have a great amount of to-dos on Today list? In this case, the workflow can need some time to fetch your to-dos, so you just need waiting enough.

If that is not the cause of your issue, please provide the logs by using the [workflow debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/).

**Comment by haakonstorm** [comment] 2019-04-19 03:20
Hah, that fixed it, I had to let it sit for close to a minute. After that, now everything works instantly. Great workflow!

**Comment by xilopaint** [comment] 2019-04-19 05:51
Good to know is everything ok to you. I'm closing the issue.

**Closed as completed by xilopaint** 2019-04-19 05:51 UTC
